--liquibase formatted sql
--changeset jalaj:001-create-vehicles

CREATE TABLE vehicles (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          owner_name VARCHAR(100),
                          vehicle_number VARCHAR(150),
                          vehicle_type VARCHAR(30),
                          status VARCHAR(20),
                          created_at TIMESTAMP
);